# This is a basic workflow to help you get started with Actions

name: PBCB_CI
on: workflow_dispatch

jobs: 
  test-api:
   runs-on: ubuntu-latest
   steps:
   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Create dir
        run: |
          mkdir NM
      
    # install node on the runner
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          
     # Install newman globally, the the reporter for slack and install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-slackreporter
          npm install -g newman-reporter-htmlextra
        
      # run the postman collection 
      - name: Run Tests
        run: newman run "general_examples_test_(test&_BDD).json" -r cli,htmlextra --reporter-htmlextra-export NM/report15.html
        
      # upload the reports to   
      - name: Output the results
        uses: actions/upload-artifact@v3
        with:
          name: Reports
          path: NM
    

  
